### ISSUE TITLE
Validation policies: what happens when a user doesn't answer a question ?

### ISSUE THREAD

**Issue by Yourgene** [gardners/surveysystem#5]
What should happen when a user clicks 'Next' without answering a question :

- an error appears on the user browser, asking him to answer the question

- an 'empty' answer is sent to the server, with a specific keyword (question_not_answered for example)

- another action ?

**Comment by wall0159** [comment]
I don't know -- let's discuss this today at the meeting

**Comment by gardners** [comment]
Did we come up with an answer for this?

**Comment by wall0159** [comment]
I've had a conversation with Andrew and Peter about this. I think the best way forward is to introduce another field into the question specification that describes whether the question is mandatory or not. **For now, all questions are mandatory, so it is not essential to implement this immediately.** 

Joerg, perhaps you can introduce some code in the front-end so that it will not accept a 'continue', etc, until the user has entered a valid response to the question. In future, we can add the extra field so that the front end first checks whether the question is mandatory before enforcing this. Sound reasonable?

**Comment by gardners** [comment]
Ok. Sounds fine. We already have a flags field that can be used for this purpose.

**Comment by gardners** [comment]
Added flag for this. See survey.h for flag values.

Note that this still leaves a problem: If a user hits next on a non-mandatory question, then the next_question logic will most likely still offer the same question for answering, because it doesn't know that the question has been skipped.  Thus when skipping an answer, you will still need to have a convention for marking the question as skipped, i.e., by having a special answer value to indicate this.

**Comment by RoboSparrow** [comment]
@Yourgene , @wall0159 Sure, will do.

**Comment by RoboSparrow** [comment]
While frontend validation is fine for now I see the need to discuss this. 
Frontend validation can be easily hacked via browser console or might be disabled via a corrupted browser. 
Also the backend endpoints are more or less exposed and act like a REST API which is (currently) writable for anyone. Think import scripts, crons etc..

Validation options:

```
1) only frontend: 
 + usability, speed
 - data integrity cannot be guaranteed
 
2) only backend:
 + data integrity 
 - slow, validation result only available after request 
 
2) dual layer: backend and frontend:
 + data integrity 
 - all the problems split solutions have
```
